### ISSUE TITLE
Xin chi tiết về 2 task này

### ISSUE THREAD

**Issue by hanaa12G** [thesis-edu-conference/wiki#2]
**Assign to**: Phúc
**Estimate deadline**: 3d

Hoàn thành login và phân quyền
- [ ] Email confirmation (@khoa) 
- [ ] Đăng nhập bằng email của Google (@khoa)

2 cái này cụ thể là làm gì á?

**Comment by 147phuc23** [comment]
cái đăng nhập bằng email thông qua google phải dùng AuthO2.
còn cái email confỉmation thì tui làm được rồi.
